/**
 * Master list of research sectors used across the platform.
 * Used in: Sector Thesis page, Research Pipeline sector selection,
 * and Stage 0 prompt to constrain sector classification.
 */
export const SECTORS = [
  'Agro Chemicals',
  'Air Transport Service',
  'Alcoholic Beverages',
  'Auto Ancillaries',
  'Automobile',
  'Banks',
  'Bearings',
  'Cables',
  'Capital Goods',
  'Castings, Forgings & Fastners',
  'Cement',
  'Ceramics & Sanitaryware',
  'Chemicals',
  'Construction',
  'Consumer Durables',
  'Credit Rating Agencies',
  'Diamond, Gems and Jewellery',
  'Diversified / Others',
  'E-Commerce / App Based Aggregator',
  'Edible Oil',
  'Education',
  'Electronics',
  'Engineering',
  'Entertainment',
  'Fertilizers',
  'Finance',
  'FMCG',
  'Gas Distribution',
  'Glass & Glass Products',
  'Healthcare',
  'Hotels & Restaurants',
  'Infrastructure',
  'Insurance',
  'IT / Technology',
  'Leather',
  'Logistics',
  'Marine Port & Services',
  'Media',
  'Metals (Non-Ferrous)',
  'Mining & Mineral Products',
  'Oil & Gas',
  'Packaging',
  'Paints / Varnish',
  'Paper',
  'Pharmaceuticals',
  'Plantation & Plantation Products',
  'Plastic Products',
  'Power',
  'Printing & Stationery',
  'Quick Service Restaurant',
  'Railways',
  'Readymade Garments / Apparells',
  'Real Estate',
  'Refractories',
  'Retail',
  'Shipping',
  'Steel',
  'Stock / Commodity Brokers',
  'Sugar',
  'Telecom',
  'Textiles',
  'Tobacco Products',
  'Tyres',
] as const;

export type SectorName = (typeof SECTORS)[number];
